dubbo:
  application:
    name: dubbo-customer-manager
  registry:
    address: zookeeper://172.16.30.70:2181
  protocol:
    name: dubbo
    port: 21001

images:
  relativePaths: /pic/**
  absolutePaths: /data/nfsshare/upload/picture
  uri: https://sp-uat.qifenqian.com/
  relativePath: /pic/


