dubbo:
  application:
    name: dubbo-customer-manager
  registry:
    address: zookeeper://192.168.1.131:2181
  protocol:
    name: dubbo
    port: 21001

images:
  relativePaths: /pic/**
  absolutePaths: D://picture
  uri: https://sp.qifenqian.com/
  relativePath: /pic/

spring:
  redis:
    database: 0
    host: 192.168.1.19
    port: 6379
    password: pass123
    timeout: 20000
    pool:
    jedis:
      pool:
        max-active: 68
        min-idle: 0
        max-idle: 8
        max-wait: -1
