spring:
  datasource:
    url: jdbc:mysql://192.168.1.17:3306/stcdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: stc_web_user
    password: 123456

server:
  port: 8089


dubbo:
  application:
    name: dubbo-customer-manager
  registry:
    address: zookeeper://192.168.1.159:2181
  protocol:
    name: dubbo
    port: 21001

redis:
  host: 192.168.1.19
  auth: pass123
  port: 6379
  #连接超时时间(毫秒)
  timeout: 3000
  pool:
    #最大连接数(负数表示没有限制)
    max-active: 100
    #最大空闲连接
    max-idle: 10
    #最大阻塞等待时间(负数表示没有限制)
    max-wait: 100000


swagger.enable: true

